# Generated by Django 2.2.4 on 2020-02-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfic',
            name='fandom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanfics', to='fanfics.Fandom'),
        ),
    ]
