# Generated by Django 2.2.4 on 2020-02-15 20:56

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('fanfics', '0002_auto_20200215_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='nsfw',
            field=models.BooleanField(default=False, help_text='Czy fanfic zawiera treści przeznaczone dla osób dorosłych?'),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Podaj słowa kluczowe, które najbardziej oddają twój fanfic.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='fandom',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Podaj słowa kluczowe, które najbardziej oddają twój fandom.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
