# Generated by Django 2.2.4 on 2020-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0003_auto_20200215_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
